[package]
name = "matchstick"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.1"
hdrhistogram = "7.5.4"
http = "1.4.0"
inferno = "0.12.4"
reqwest = "0.13.1"
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.17"
tokio = "1.49.0"
tokio-tungstenite = "0.28.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
